### ISSUE TITLE
PowerEdge 1800

### ISSUE THREAD

**Issue by skymike** [arnuschky/dell-bmc-firmware#1]
Hi Arnuschky,
I am following your github and i could find Dell PE 1800 and you have mentioned that it should work on generation 8 dell servers, would it be applicable on PowerEdge 1800?

I have looked everywhere and found your blog and i wanted to make sure before i will buy new fans

Any help will be highly appreciated! :-)
Thanks,
Michael.

**Comment by arnuschky** [comment]
Hello,

It should work on a PE 1800 without problems. You just need to identify the proper setting
in the script. No guarantees though, I think you're the first one to try with a 1800.

Cheers

On 04/08/15 13:36, skymike wrote:

> Hi Arnuschky,
> I am following your github and i could find Dell PE 1800 and you have
> mentioned that it should work on generation 8 dell servers, would it be
> applicable on PowerEdge 1800?
> 
> I have looked everywhere and found your blog and i wanted to make sure
> before i will buy new fans
> 
> Any help will be highly appreciated! :-)
> Thanks,
> Michael.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arnuschky/dell-bmc-firmware/issues/1.

## 

Arne Brutschy abrutschy@xylon.de

**Comment by skymike** [comment]
Hi again,
Thanks for the reply, any recommendations on  identifying the proper setting in the script?
should i look in the PE 1800 BMC .bin file maybe?

**Comment by arnuschky** [comment]
Just follow the instructions on the website/from the script. It should give you a limited number of options (2-4 systems). You can usually identify your system by comparing the number of fans. Go ahead, execute it - nothing to lose just by modifying the firmware. If the script executes without complaint, the modified firmware should work.

You might require a few trials until you identify the proper system. This is not a problem and does not harm your machine.

**Comment by skymike** [comment]
It worked like a charm! (#systems['MUS'] = 'PowerEdge 1800' was my redemption
I was cheap and impatient so i tried with my old fans unsurprisingly it didn't work properly and now i am waiting for the new fans to arrive, 
however i do have 1 question i couldn't find what is the recommended redaction , half of the current thresholds or less.
Thanks in advance!

**Comment by arnuschky** [comment]
You have to experiment to see what works. :) Half of your the RPM of your new fans seems like a reasonable value. For sure, the threshold must be below the RPM of your new fans...
